apiVersion: apps/v1
kind: Deployment
metadata: { name: web }
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
      - name: web
        image: nginx:1.27-alpine
        args:
        {{- range .Values.args }}
          - {{ . }}
        {{- end }}
