image: docker.io/jenkins/jenkins:lts-jdk17
replicaCount: 1
service:
  port: 8080
persistence:
  size: 2Gi
resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
